### PR TITLE
Custom extensions and SANs

### PR DESCRIPTION
**Pull request by upcFrost**
Hi,
This code allows to change some values that were hardcoded previously, e.g. SANs (DNS only while IP can be used sometimes) and certificate extensions (distributed systems need client+server certificates, and sometime even smth completely custom is needed).
Also, i've added these option to the readme.

### CODE REVIEW

**Comment by bellpeterm** [comment]
Thanks for the PR!  I'm travelling the next couple days so I won't be able to merge immediately.  To speed up testing and protect against future regressions, could you write an RSpec test for the peer and custom types?

**Comment by upcFrost** [comment]
Sure, np

**Comment by upcFrost** [comment]
Hi, rspec tests for peer and custom types, as well as for the DNS+IP mixed SAN, finished, all green. Plz check when you'll have time

**Comment by bellpeterm** [comment]
Thanks for getting those tests added.  I apologize that I haven't had a chance to verify and merge but this hasn't dropped off my radar.

**Comment by upcFrost** [comment]
Just a friendly reminder about the PR if you have some time

**Comment by bellpeterm** [comment]
Thanks for the reminder and sorry again for the delay.  Merged and uploaded a new version to Rubygems.

**Comment by upcFrost** [comment]
Cool, thanks :+1:

**Pull request merged**
